import React, { useState, useMemo, useEffect } from "react";
import { Button } from "../Button";
import { LessonObjective } from "../../types";
import {
  TAXONOMY_AREAS,
  TAXONOMY_SUB_CATEGORIES,
  BLOOMS_TAXONOMY,
  CEFR_LEVELS,
  PREDEFINED_OBJECTIVES,
  buildObjectiveText,
  ObjectiveArea
} from "../../data/learningObjectives";

interface LessonObjectivesEditorProps {
  objectives: LessonObjective[];
  onChange: (updatedObjectives: LessonObjective[]) => void;
}

export function LessonObjectivesEditor({
  objectives = [],
  onChange
}: LessonObjectivesEditorProps) {
  // Mode: "builder" (4-Dropdown Taxonomy Builder), "shortcuts" (Predefined templates), "freeform" (custom text)
  const [editorMode, setEditorMode] = useState<"builder" | "shortcuts" | "freeform">("builder");

  // --- 1. State for 4-Dropdown Builder ---
  const [buildArea, setBuildArea] = useState<ObjectiveArea>("Grammar");
  const [buildSubCategory, setBuildSubCategory] = useState<string>("");
  const [buildBloom, setBuildBloom] = useState<string>("");
  const [buildLevel, setBuildLevel] = useState<string>("B1");
  const [customizedWording, setCustomizedWording] = useState<string>("");
  const [isWordingEdited, setIsWordingEdited] = useState<boolean>(false);

  // Sync subcategory when Area changes
  const subCategoryOptions = useMemo(() => {
    return TAXONOMY_SUB_CATEGORIES[buildArea] || [];
  }, [buildArea]);

  useEffect(() => {
    if (subCategoryOptions.length > 0) {
      setBuildSubCategory(subCategoryOptions[0]);
    }
  }, [subCategoryOptions]);

  // Set default Bloom level on load
  useEffect(() => {
    if (BLOOMS_TAXONOMY.length > 0 && !buildBloom) {
      setBuildBloom(BLOOMS_TAXONOMY[2].level); // Default to "Apply / Use in context"
    }
  }, [buildBloom]);

  // Generate objective text dynamically
  const autoGeneratedText = useMemo(() => {
    if (!buildArea || !buildSubCategory || !buildBloom || !buildLevel) return "";
    return buildObjectiveText(buildArea, buildSubCategory, buildBloom, buildLevel);
  }, [buildArea, buildSubCategory, buildBloom, buildLevel]);

  // Sync auto-generated text to customizedWording unless the user explicitly edited it
  useEffect(() => {
    if (!isWordingEdited) {
      setCustomizedWording(autoGeneratedText);
    }
  }, [autoGeneratedText, isWordingEdited]);

  // --- 2. State for Curated Shortcuts ---
  const [shortcutFilterArea, setShortcutFilterArea] = useState<ObjectiveArea>("Grammar");
  const [shortcutFilterLevel, setShortcutFilterLevel] = useState<string>("B1");

  const filteredShortcuts = useMemo(() => {
    return PREDEFINED_OBJECTIVES.filter(
      (obj) => obj.category === shortcutFilterArea && obj.level === shortcutFilterLevel
    );
  }, [shortcutFilterArea, shortcutFilterLevel]);

  // --- 3. State for Custom/Freeform ---
  const [freeformArea, setFreeformArea] = useState<ObjectiveArea>("Grammar");
  const [freeformLevel, setFreeformLevel] = useState<string>("B1");
  const [freeformText, setFreeformText] = useState<string>("");

  // --- Handlers ---
  const handleAddFromBuilder = () => {
    if (!customizedWording.trim()) {
      alert("Objective text cannot be empty.");
      return;
    }

    const newObjective: LessonObjective = {
      id: `obj_tax_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      category: buildArea,
      subCategory: buildSubCategory,
      cognitiveAction: buildBloom,
      level: buildLevel,
      text: customizedWording.trim(),
      isCustom: true
    };

    // Check if duplicate
    if (objectives.some((o) => o.text === newObjective.text)) {
      alert("This precise learning objective is already added.");
      return;
    }

    onChange([...objectives, newObjective]);
    setIsWordingEdited(false);
  };

  const handleAddShortcut = (shortcut: typeof PREDEFINED_OBJECTIVES[0]) => {
    // Check if duplicate
    if (objectives.some((o) => o.text === shortcut.text || o.id === shortcut.id)) {
      alert("This objective is already added to the lesson.");
      return;
    }

    const newObjective: LessonObjective = {
      id: shortcut.id,
      category: shortcut.category,
      subCategory: shortcut.subCategory,
      cognitiveAction: shortcut.cognitiveAction,
      level: shortcut.level,
      text: shortcut.text,
      isCustom: false
    };

    onChange([...objectives, newObjective]);
  };

  const handleAddFreeform = () => {
    if (!freeformText.trim()) {
      alert("Please specify objective text.");
      return;
    }

    const newObjective: LessonObjective = {
      id: `obj_free_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      category: freeformArea,
      subCategory: "General Concept",
      cognitiveAction: "Custom Application",
      level: freeformLevel,
      text: freeformText.trim(),
      isCustom: true
    };

    onChange([...objectives, newObjective]);
    setFreeformText("");
  };

  const handleRemove = (id: string) => {
    onChange(objectives.filter((o) => o.id !== id));
  };

  // --- Helper badge styles ---
  const getCefrBadgeStyle = (level: string) => {
    switch (level) {
      case "A1":
        return "bg-green-100 text-green-700 border-green-200";
      case "A2":
        return "bg-blue-100 text-blue-700 border-blue-200";
      case "B1":
        return "bg-yellow-100 text-yellow-700 border-yellow-200";
      case "B2":
        return "bg-orange-100 text-orange-700 border-orange-200";
      case "C1":
        return "bg-purple-100 text-purple-700 border-purple-200";
      case "C2":
        return "bg-red-100 text-red-700 border-red-200";
      default:
        return "bg-indigo-100 text-indigo-700 border-indigo-200";
    }
  };

  const getAreaIcon = (area: string) => {
    switch (area) {
      case "Grammar":
        return "⚙️";
      case "Vocabulary":
        return "📚";
      case "Functional Language":
        return "💬";
      case "Pronunciation":
        return "🗣️";
      default:
        return "🎯";
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center border-b border-primary-light/50 pb-2">
        <h4 className="font-bold text-[15px] text-primary-dark">
          Lesson Learning Objectives
        </h4>
        <span className="text-xs text-text-secondary font-medium">
          {objectives.length} active objective{objectives.length !== 1 ? "s" : ""}
        </span>
      </div>

      {/* Active Objectives List */}
      {objectives.length === 0 ? (
        <div className="text-center py-6 px-4 bg-neutral-bg rounded-xl border border-dashed border-primary-light/80">
          <p className="text-sm text-text-secondary">
            No learning objectives specified for this lesson yet.
          </p>
          <p className="text-xs text-text-secondary/70 mt-1">
            Build pedagogical objectives below using the 4-dropdown taxonomy.
          </p>
        </div>
      ) : (
        <div className="space-y-3 max-h-[300px] overflow-y-auto pr-2">
          {objectives.map((obj) => (
            <div
              key={obj.id}
              className="flex items-start justify-between p-3.5 bg-white border border-primary-light rounded-xl hover:shadow-sm transition-all"
            >
              <div className="flex items-start gap-3">
                <span className="text-lg mt-0.5">{getAreaIcon(obj.category)}</span>
                <div className="space-y-1">
                  <div className="flex items-center gap-1.5 flex-wrap">
                    <span
                      className={`text-[10px] font-extrabold border px-2 py-0.5 rounded uppercase ${getCefrBadgeStyle(
                        obj.level
                      )}`}
                    >
                      {obj.level}
                    </span>
                    <span className="text-[10px] bg-primary-light/10 text-primary-dark border border-primary-light/30 px-2 py-0.5 rounded font-extrabold uppercase">
                      {obj.category}
                    </span>
                    {obj.subCategory && (
                      <span className="text-[10px] bg-neutral-bg text-text-secondary border border-primary-light/30 px-2 py-0.5 rounded font-semibold">
                        {obj.subCategory}
                      </span>
                    )}
                    {obj.cognitiveAction && (
                      <span className="text-[10px] bg-amber-50 text-amber-800 border border-amber-200 px-2 py-0.5 rounded font-medium">
                        {obj.cognitiveAction}
                      </span>
                    )}
                    {obj.isCustom && (
                      <span className="text-[9px] bg-indigo-50 border border-indigo-100 text-indigo-600 px-1 rounded font-bold uppercase">
                        Custom
                      </span>
                    )}
                  </div>
                  <p className="text-[13px] text-text-primary leading-relaxed font-semibold">
                    {obj.text}
                  </p>
                </div>
              </div>
              <button
                onClick={() => handleRemove(obj.id)}
                className="text-text-secondary hover:text-red-500 hover:bg-red-50 p-1.5 rounded-lg transition-colors ml-4 shrink-0"
                title="Remove objective"
              >
                ✕
              </button>
            </div>
          ))}
        </div>
      )}

      {/* Editor Box */}
      <div className="bg-neutral-bg border border-primary-light/60 rounded-xl p-4 space-y-4">
        {/* Toggle Mode Menu */}
        <div className="flex items-center justify-between border-b border-primary-light/40 pb-3">
          <div className="flex gap-2">
            <button
              onClick={() => setEditorMode("builder")}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                editorMode === "builder"
                  ? "bg-primary text-white shadow-sm"
                  : "bg-white text-text-secondary border border-primary-light hover:bg-primary-light/10"
              }`}
            >
              🎯 4-Dropdown Builder
            </button>
            <button
              onClick={() => setEditorMode("shortcuts")}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                editorMode === "shortcuts"
                  ? "bg-primary text-white shadow-sm"
                  : "bg-white text-text-secondary border border-primary-light hover:bg-primary-light/10"
              }`}
            >
              ⚡ Predefined Shortcuts
            </button>
            <button
              onClick={() => setEditorMode("freeform")}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                editorMode === "freeform"
                  ? "bg-primary text-white shadow-sm"
                  : "bg-white text-text-secondary border border-primary-light hover:bg-primary-light/10"
              }`}
            >
              ✍️ Freeform Custom
            </button>
          </div>
          <span className="text-[11px] font-semibold text-text-secondary italic">
            English language guidelines
          </span>
        </div>

        {/* Builder View */}
        {editorMode === "builder" && (
          <div className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
              {/* Dropdown 1: Area */}
              <div>
                <label className="block text-[11px] font-bold text-primary-dark mb-1">
                  1. Major Dimension (Area)
                </label>
                <select
                  value={buildArea}
                  onChange={(e) => setBuildArea(e.target.value as ObjectiveArea)}
                  className="w-full bg-white border border-primary-light rounded-lg p-2 text-xs font-bold text-text-primary focus:outline-none focus:ring-1 focus:ring-primary"
                >
                  {TAXONOMY_AREAS.map((area) => (
                    <option key={area} value={area}>
                      {getAreaIcon(area)} {area}
                    </option>
                  ))}
                </select>
              </div>

              {/* Dropdown 2: Specific Subcategory */}
              <div>
                <label className="block text-[11px] font-bold text-primary-dark mb-1">
                  2. Specific Sub-category
                </label>
                <select
                  value={buildSubCategory}
                  onChange={(e) => setBuildSubCategory(e.target.value)}
                  className="w-full bg-white border border-primary-light rounded-lg p-2 text-xs font-semibold text-text-primary focus:outline-none focus:ring-1 focus:ring-primary"
                >
                  {subCategoryOptions.map((sub) => (
                    <option key={sub} value={sub}>
                      {sub}
                    </option>
                  ))}
                </select>
              </div>

              {/* Dropdown 3: Cognitive Action (Bloom) */}
              <div>
                <label className="block text-[11px] font-bold text-primary-dark mb-1">
                  3. Cognitive Action (Bloom)
                </label>
                <select
                  value={buildBloom}
                  onChange={(e) => setBuildBloom(e.target.value)}
                  className="w-full bg-white border border-primary-light rounded-lg p-2 text-xs font-semibold text-text-primary focus:outline-none focus:ring-1 focus:ring-primary"
                >
                  {BLOOMS_TAXONOMY.map((b) => (
                    <option key={b.level} value={b.level} title={b.description}>
                      {b.level}
                    </option>
                  ))}
                </select>
              </div>

              {/* Dropdown 4: Level */}
              <div>
                <label className="block text-[11px] font-bold text-primary-dark mb-1">
                  4. CEFR Level
                </label>
                <select
                  value={buildLevel}
                  onChange={(e) => setBuildLevel(e.target.value)}
                  className="w-full bg-white border border-primary-light rounded-lg p-2 text-xs font-bold text-text-primary focus:outline-none focus:ring-1 focus:ring-primary"
                >
                  {CEFR_LEVELS.map((lvl) => (
                    <option key={lvl} value={lvl}>
                      {lvl} Level
                    </option>
                  ))}
                </select>
              </div>
            </div>

            {/* Bloom description banner */}
            {buildBloom && (
              <div className="bg-amber-50 border border-amber-200/60 rounded-lg p-2.5 text-[11px] text-amber-800 leading-relaxed">
                <strong>Pedagogical Context:</strong>{" "}
                {BLOOMS_TAXONOMY.find((b) => b.level === buildBloom)?.description}
                <span className="block mt-0.5 text-amber-600/90 font-medium">
                  <strong>Example Activity:</strong>{" "}
                  {BLOOMS_TAXONOMY.find((b) => b.level === buildBloom)?.example}
                </span>
              </div>
            )}

            {/* Live Preview & Customize Area */}
            <div className="border border-primary-light/50 bg-white rounded-lg p-3 space-y-2">
              <div className="flex justify-between items-center">
                <span className="text-[10px] font-extrabold uppercase tracking-wider text-text-secondary">
                  Competency Sentence Preview
                </span>
                <button
                  onClick={() => {
                    setIsWordingEdited(!isWordingEdited);
                    if (isWordingEdited) {
                      setCustomizedWording(autoGeneratedText);
                    }
                  }}
                  className="text-[10px] text-primary font-bold hover:underline"
                >
                  {isWordingEdited ? "↩ Reset to Automatic" : "✏️ Customize Text"}
                </button>
              </div>

              {isWordingEdited ? (
                <textarea
                  value={customizedWording}
                  onChange={(e) => setCustomizedWording(e.target.value)}
                  className="w-full text-xs font-medium bg-neutral-bg p-2 rounded border border-primary-light focus:outline-none min-h-[50px]"
                />
              ) : (
                <p className="text-xs font-bold text-primary-dark bg-neutral-bg/30 p-2 rounded border border-neutral-bg select-all">
                  {customizedWording}
                </p>
              )}
            </div>

            {/* Add Button */}
            <div className="flex justify-end">
              <Button
                variant="primary"
                onClick={handleAddFromBuilder}
                className="py-1.5 px-4 text-xs font-bold shadow-sm"
              >
                + Add Objective to Lesson
              </Button>
            </div>
          </div>
        )}

        {/* Shortcuts View */}
        {editorMode === "shortcuts" && (
          <div className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-[11px] font-bold text-text-secondary mb-1">
                  Filter Category
                </label>
                <select
                  value={shortcutFilterArea}
                  onChange={(e) => setShortcutFilterArea(e.target.value as ObjectiveArea)}
                  className="w-full bg-white border border-primary-light rounded-lg p-2 text-xs font-medium focus:outline-none"
                >
                  {TAXONOMY_AREAS.map((area) => (
                    <option key={area} value={area}>
                      {getAreaIcon(area)} {area}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-[11px] font-bold text-text-secondary mb-1">
                  Filter CEFR Level
                </label>
                <select
                  value={shortcutFilterLevel}
                  onChange={(e) => setShortcutFilterLevel(e.target.value)}
                  className="w-full bg-white border border-primary-light rounded-lg p-2 text-xs font-medium focus:outline-none"
                >
                  {CEFR_LEVELS.map((lvl) => (
                    <option key={lvl} value={lvl}>
                      {lvl} level
                    </option>
                  ))}
                </select>
              </div>
            </div>

            {/* Matches list */}
            <div className="space-y-2">
              <label className="block text-[11px] font-bold text-text-secondary">
                Curated Predefined Objectives Matches ({filteredShortcuts.length})
              </label>
              {filteredShortcuts.length === 0 ? (
                <div className="p-4 bg-white border border-dashed border-primary-light/80 rounded-lg text-center text-xs text-text-secondary italic">
                  No predefined shortcuts found matching these filters. Try the 4-Dropdown Builder!
                </div>
              ) : (
                <div className="space-y-2 max-h-[160px] overflow-y-auto pr-1">
                  {filteredShortcuts.map((sc) => (
                    <div
                      key={sc.id}
                      className="flex items-center justify-between p-2.5 bg-white border border-primary-light rounded-lg hover:border-primary transition-all text-xs"
                    >
                      <div className="flex-1 pr-3">
                        <span className="font-bold text-[10px] text-amber-700 bg-amber-50 px-1.5 py-0.5 rounded border border-amber-200 mr-1.5">
                          {sc.subCategory}
                        </span>
                        <span className="font-medium text-text-primary">{sc.text}</span>
                      </div>
                      <Button
                        variant="outline"
                        onClick={() => handleAddShortcut(sc)}
                        className="py-1 px-2.5 text-[10px] shrink-0 font-extrabold border-primary-light text-primary hover:bg-primary-light/15"
                      >
                        + Add
                      </Button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

        {/* Freeform custom text entry */}
        {editorMode === "freeform" && (
          <div className="space-y-3">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-[11px] font-bold text-text-secondary mb-1">
                  Aspect / Area
                </label>
                <select
                  value={freeformArea}
                  onChange={(e) => setFreeformArea(e.target.value as ObjectiveArea)}
                  className="w-full bg-white border border-primary-light rounded-lg p-2 text-xs font-medium focus:outline-none"
                >
                  {TAXONOMY_AREAS.map((area) => (
                    <option key={area} value={area}>
                      {getAreaIcon(area)} {area}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-[11px] font-bold text-text-secondary mb-1">
                  Target CEFR Level
                </label>
                <select
                  value={freeformLevel}
                  onChange={(e) => setFreeformLevel(e.target.value)}
                  className="w-full bg-white border border-primary-light rounded-lg p-2 text-xs font-medium focus:outline-none"
                >
                  {CEFR_LEVELS.map((lvl) => (
                    <option key={lvl} value={lvl}>
                      {lvl} level
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div>
              <label className="block text-[11px] font-bold text-text-secondary mb-1">
                Custom Objective Description (English)
              </label>
              <textarea
                placeholder="E.g., Can recognize the difference between direct and indirect object pronouns in simple conversational dialogue..."
                value={freeformText}
                onChange={(e) => setFreeformText(e.target.value)}
                className="w-full bg-white border border-primary-light rounded-lg p-2 text-xs min-h-[70px] focus:outline-none focus:ring-1 focus:ring-primary"
              />
            </div>

            <div className="flex justify-end">
              <Button
                variant="primary"
                onClick={handleAddFreeform}
                className="py-1.5 px-3 text-xs font-bold shadow-sm"
              >
                Add Freeform Objective
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
